name: Lint Pull Request

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

permissions: {}

jobs:
  lint-pr:
    name: Lint PR Title
    permissions:
      contents: read
    uses: equinor/ops-actions/.github/workflows/commitlint.yml@04eae1eb46f52241507c15ab0e874b9063ccf4d0 # v9.40.1
    with:
      message: ${{ github.event.pull_request.title }}
